### ISSUE TITLE
ModuleNotFound error for 'requests_ntlm' when trying to run test_IBMQuantumExperience.py

### ISSUE THREAD

**Issue by skepticallemur** [QISKit/qiskit-api-py#58]
The IBMQuantumExperience package and the requests_ntlm package both were installed though pip, but whenever I try to run the tests, no tests are run and the error thrown is:

```
runfile('/home/quantummechanic/Packages/qiskit-api-py/test/test_IBMQuantumExperience.py', wdir='/home/quantummechanic/Packages/qiskit-api-py/test')
Reloaded modules: config, projectq, projectq._version, projectq.cengines, projectq.cengines._basics, projectq.ops, projectq.ops._basics, projectq.types, projectq.types._qubit, projectq.ops._command, projectq.ops._metagates, projectq.ops._gates, projectq.ops._qftgate, projectq.ops._qubit_operator, projectq.ops._shortcuts, projectq.ops._time_evolution, projectq.cengines._cmdmodifier, projectq.cengines._ibmcnotmapper, projectq.meta, projectq.meta._dirtyqubit, projectq.meta._qubitplacement, projectq.meta._loop, projectq.meta._util, projectq.meta._compute, projectq.meta._control, projectq.meta._dagger, projectq.backends, projectq.backends._printer, projectq.backends._circuits, projectq.backends._circuits._to_latex, projectq.backends._circuits._drawer, projectq.backends._sim, projectq.backends._sim._simulator, projectq.backends._sim._cppsim, projectq.backends._sim._classical_simulator, projectq.backends._resource, projectq.backends._ibm, projectq.backends._ibm._ibm, projectq.backends._ibm._ibm_http_client, projectq.cengines._manualmapper, projectq.cengines._main, projectq.cengines._optimize, projectq.cengines._replacer, projectq.cengines._replacer._decomposition_rule, projectq.cengines._replacer._decomposition_rule_set, projectq.cengines._replacer._replacer, projectq.cengines._tagremover, projectq.cengines._testengine
Traceback (most recent call last):

  File "<ipython-input-25-e9e887411e77>", line 1, in <module>
    runfile('/home/quantummechanic/Packages/qiskit-api-py/test/test_IBMQuantumExperience.py', wdir='/home/quantummechanic/Packages/qiskit-api-py/test')

  File "/home/quantummechanic/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/quantummechanic/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/quantummechanic/Packages/qiskit-api-py/test/test_IBMQuantumExperience.py", line 13, in <module>
    from IBMQuantumExperience import IBMQuantumExperience  # noqa

  File "../IBMQuantumExperience/IBMQuantumExperience.py", line 15, in <module>
    from requests_ntlm import HttpNtlmAuth

ModuleNotFoundError: No module named 'requests_ntlm'
```

**Comment by diego-plan9** [comment]
@skepticallemur, can you provide more information about your environment?

It seems you are trying to run the tests from a `spider` interpreter or via an IDE (`runfile(...)`), which might not have the required dependencies properly installed. Can you check that `requests_ntlm` is really installed in your environment, by executing in the same terminal:

```
import requests_ntlm
```

**Comment by skepticallemur** [comment]
Yes, I am using the Spyder environment.

Running that in the local console produces the same error 
`
import requests_ntlm
Traceback (most recent call last):

  File "<ipython-input-3-8e7368e2c3ff>", line 1, in <module>
    import requests_ntlm

ModuleNotFoundError: No module named 'requests_ntlm' 
`

**Comment by diego-plan9** [comment]
Can you please double-check the installation status of the `requests_ntlm` package _in the environment you are executing the samples_ you are providing? Your latest snippet (ie. trying a bare `import requests_ntlm`, and failing with a `ModuleNotFoundError`) points towards the package effectively not being available to that Python interpreter, which in turn seems to be specific to your setup - without more details, we unfortunately cannot reproduce it.

As a suggestion, can you try installing the package inside a spyder console via (note the `!` at the beginning of the line):
```
!pip install requests_ntlm
```
